### PR TITLE
Update your profile page

### PR DESCRIPTION
**Pull request by martindev727**

### CODE REVIEW

**Comment by rphovley** [comment]
@martindev727 Same items need to be fixed on this this that need to be fixed on "Register" page. Also, the text on inputs needs to match designs

I believe everything is good except for text color. 
screen shot 2018-09-04 at 8 30 46 am

**Comment by rphovley** [comment]
Same thing with the yes/no option that resets when checkbox is selected

**Comment by martindev727** [comment]
Radio validation fixed.

**Comment by rphovley** [comment]
Between the pixel width of 670 and 700 or so the submit buttons are positioned oddly

screen shot 2018-09-05 at 11 03 25 am

**Pull request closed without merging**
